# Generated by Django 4.2 on 2023-04-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('own_car', models.BooleanField()),
                ('own_realty', models.BooleanField()),
                ('children_count', models.PositiveSmallIntegerField()),
                ('annual_income', models.PositiveIntegerField()),
                ('income_type', models.CharField()),
                ('education_level', models.CharField()),
                ('family_status', models.CharField()),
                ('housing_type', models.CharField()),
                ('bday_shift', models.IntegerField()),
                ('days_employed', models.IntegerField()),
                ('has_mobile', models.BooleanField()),
                ('has_work_phone', models.BooleanField()),
                ('has_phone', models.BooleanField()),
                ('occupation_type', models.CharField(null=True)),
                ('family_members_count', models.PositiveSmallIntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
