# Generated by Django 4.2.1 on 2023-05-29 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_balance', models.PositiveIntegerField(verbose_name='Limit balance')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender')),
                ('education_level', models.PositiveSmallIntegerField(choices=[(1, 'Graduate school'), (2, 'University'), (3, 'High school'), (4, 'Others')], verbose_name='Education level')),
                ('marriage', models.PositiveSmallIntegerField(choices=[(1, 'Married'), (2, 'Single'), (3, 'Others')], verbose_name='Marriage status')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('pay_1', models.PositiveIntegerField()),
                ('pay_2', models.PositiveIntegerField()),
                ('pay_3', models.PositiveIntegerField()),
                ('pay_4', models.PositiveIntegerField()),
                ('pay_5', models.PositiveIntegerField()),
                ('pay_6', models.PositiveIntegerField()),
                ('bill_amt_1', models.PositiveIntegerField()),
                ('bill_amt_2', models.PositiveIntegerField()),
                ('bill_amt_3', models.PositiveIntegerField()),
                ('bill_amt_4', models.PositiveIntegerField()),
                ('bill_amt_5', models.PositiveIntegerField()),
                ('bill_amt_6', models.PositiveIntegerField()),
                ('pay_amt_1', models.PositiveIntegerField()),
                ('pay_amt_2', models.PositiveIntegerField()),
                ('pay_amt_3', models.PositiveIntegerField()),
                ('pay_amt_4', models.PositiveIntegerField()),
                ('pay_amt_5', models.PositiveIntegerField()),
                ('pay_amt_6', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
