# Generated by Django 4.2 on 2023-04-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0002_creditapplication_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='education_level',
            field=models.CharField(choices=[('Secondary / secondary special', 'Secondary / secondary special'), ('Higher education', 'Higher education'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='family_status',
            field=models.CharField(choices=[('Civil marriage', 'Civil marriage'), ('Single / not married', 'Single / not married'), ('Separated', 'Separated'), ('Married', 'Married'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='housing_type',
            field=models.CharField(choices=[('House / apartment', 'House / apartment'), ('Municipal apartment', 'Municipal apartment'), ('With parents', 'With parents'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='income_type',
            field=models.CharField(choices=[('Working', 'Working'), ('Commercial associate', 'Commercial associate'), ('Other', 'Other')]),
        ),
    ]
